### ISSUE TITLE
Проверка ДЗ1 СУБД

### ISSUE THREAD

**Issue by konopkin11** [go-park-mail-ru/2024_1_Refugio#20]
1.  Выписаны только функциональные зависимости от первичного ключа, все остальные проигнорированы, хотя даже взглянув на таблицу видно, что в таблице юзеров есть точно такие же зависимости от login тк он unique
https://github.com/go-park-mail-ru/2024_1_Refugio/blame/804a3f76a366d3e4036060ed8951ba2d734ffb16/db/normalized/relations.md#L168

2. Использование serial
 https://github.com/go-park-mail-ru/2024_1_Refugio/blob/804a3f76a366d3e4036060ed8951ba2d734ffb16/db/migrations/init.sql#L4

3. При нормализации необходимо указать все потенциальные ключи и выбрать из них первичный

4. в ER диаграмме отделить первичный ключ от остальных полей (например жирной чертой), и будет вообще круто если напротив FK PK и AK напишете эти буквы) То есть id PK, avatarId FK, email AK и так далее.

**Comment by konopkin11** [comment]
UPD
1. Пропущен внешний ключ? 
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L13

2. У вас планируется больше двух гендеров? Тогда возможно 10 символов не хватит (HEAVY HELICOPTER 15 символов). Иначе может лучше check сделать на определенные два значения (равно тому или равно другому) 
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L10

3. Можно дефолтное значение указать
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L12
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L22

4. Вы же не raw password храните, может лучше назвать passwordHash?
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L7

5. Лучше вставку начальных значений вынести в отдельную миграцию (хотя бы в конец файла поставить, читать очень тяжело так)

6. Название атрибута неинформативно
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L50

7. Можно счесть за придирку) статус это о перечислении значений, как мне кажется, тут лучше бы подошло isDraft, isDeleted и так далее
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L48

8. AUTOINCREMENT не существует в постгре. Давайте договоримся хотя бы пробовать запускать миграцию, чтобы убедиться, что нет синтаксических ошибок :)

9. Таблица связи М2М. Зачем id? Обычной практикой будет сделать первичный ключ из двух айдишников - письма и юзера
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L67
То же самое
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L108

10. Правильн понимаю, что файл айди, видеоАйди это все айдишники внешнего хранилища? Может тогда сделать file_id и file_type? Либо объясните для чего нужно столько полей?
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L90

11. isNotificationsEnabled?
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L118

12. чем LENGTH() не устроил?
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/365b69512bbffe6da277a6dab4382bc1b0452acd/db/migrations/init.sql#L25

**Comment by konopkin11** [comment]
UPD
использование TIMESTAMP вместо TIMESTAMPTZ (https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_NOT_IN)

**Comment by Fedasov** [comment]
1. В avatar_id будет лежать ссылка на фото
2. Добавил проверку CHECK (gender = 'Male' OR gender = 'Female' OR gender = 'Other')
3. Дефолтное значение указал DEFAULT '2022-08-10 10:10:00'
4. Исправил на password_hash
5. Добавление значение теперь в конце файла
6. Поменял flag -> flag_important_email
7. Название полей поменял 
8. Вместо AUTOINCREMENT сделал Sequence последовательности
9. ID из М2М таблиц убрал 
10. Заменил на file_id
11. notifications_enabled
12. Поменял на LENGTH
13. Заменил на TIMESTAMPTZ
+ Добавил как просил в поля значения PK, FK и AK и уникальные ключи на таблицы тоже

**Comment by konopkin11** [comment]
Надо было все таки через pull request делать, так сильно неудобно проверять)
Помечу, какие ошибки остались.
1. ER диаграмма не рендерится
2. Забыл убрать?
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/DBMS_homework/db/normalized/relations.md#folderemail-1
3. При нормализации необходимо указать все потенциальные ключи и выбрать из них первичный - выпиши после функциональных зависимостей потенциальные ключи и выбери из них первичный.
4. Для sequence почитай про cache ( https://postgrespro.ru/docs/postgresql/10/sql-createsequence ) - возможно захочешь внедрить (не настаиваю)
5. Эт че?) текущий таймстемп использовать можно
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/e01cb0f40ee261d3f79520a81fcbc0659435dcba/db/migrations/init.sql#L12
6. может аватар_айди заменить на файл? это же тоже файл
7. Поменял flag -> flag_important_email - может лучше is_important?
8. Заменил на file_id - а тип не нужен будет? Я понимаю для чего нужны типы, просто их через enum сделать можно и соответсвенно колонку file_type TEXT. или не нужен тип?

В остальном молодец, все круто, диаграмму в виде кода посмотрел, вроде все ок

**Comment by konopkin11** [comment]
3. надо просто выписать ключи в формате {ID}. А ты продублировал функциональные зависимости
4. напиши почему не нужно (кратко)
6. ты наверное не так понял про аватарку) я имею ввиду оставить avatar_id но сделать это внешним ключем на таблицу файлов чтобы у тебя все файлы были в одном месте
8. напиши почему не нужно (кратко)

**Comment by Fedasov** [comment]
3. Исправил
4. Могут возникнуть проблемы с объектом последовательности, используя параллельно в нескольких сеансах. Из-за кеширования может возвращаться заготовленные значения, которое находится в кэше, вместо самого объекта последовательности.
5. Сделал общую таблицу file на которую теперь ссылаются avatar_id из profile и file_id из file

**Comment by ns-roxer** [comment]
https://github.com/go-park-mail-ru/2024_1_Refugio/blob/DBMS_homework/db/migrations/init.sql
Уберите, пожалуйста, явную работу с sequence, и используйте вместо этого.
https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-PARMS-GENERATED-IDENTITY
Код станет гораздо проще.

**Comment by Fedasov** [comment]
Явную работу sequence убрал. Добавил GENERATED ALWAYS AS IDENTITY

**Comment by ns-roxer** [comment]
@konopkin11 закрой, пожалуйста, issue.
